name: taskly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Local Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.2
  path: ^1.8.3

  # Micro packages
  taskly_ui:
    path: packages/taskly_ui
  taskly_api_client:
    path: packages/taskly_api_client
  taskly_graphql:
    path: packages/taskly_graphql

  # Slang
  slang_flutter: ^4.8.0
  slang: ^4.8.1

  # Code Generation
  copy_with_extension: ^6.0.1
  json_annotation: ^4.9.0

  # Device
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  taskly_commons_dependencies_dev:
    path: packages/taskly_commons_dependencies_dev
  drift_dev: ^2.14.1
  riverpod_generator: ^2.3.9
  slang_build_runner: ^4.8.0
  copy_with_extension_gen: ^6.0.1
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
