name: taskly_graphql
description: GraphQL API client for Taskly app.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.2.0

dev_dependencies:
  taskly_commons_dependencies_dev:
    path: ../taskly_commons_dependencies_dev

flutter:
  uses-material-design: true